import type { Metadata } from 'next';
import Header from './components/Header';
import Providers from './providers';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="text-white bg-slate-800">
      <body>
    <Providers><Header />
          {children}</Providers>
          
      </body>
    </html>
  );
}
